language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix: 
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e "Pkg.init()"
  - mkdir -p ~/.julia/MOpt.jl
  - cp -R ./* ~/.julia/MOpt.jl
  - julia -e 'versioninfo(); Pkg.add("FactCheck"); Pkg.add("DataFrames"); Pkg.add("Distributions"); Pkg.add("PyPlot"); Pkg.add("Reexport")'
  - julia ~/.julia/MOpt.jl/test/runtests.jl
