language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix: 
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - git config --global user.name "Travis User"
  - git config --global user.email "travis@example.net"
script:
  # - julia -e "Pkg.init()"
  # - mkdir -p ~/.julia/MOpt.jl
  # - cp -R ./* ~/.julia/MOpt.jl
  - julia -e 'Pkg.clone("git://github.com/floswald/MOpt.jl"); run(`ln -s $(pwd()) $(Pkg.dir("MOpt"))`); Pkg.pin("MOpt"); Pkg.resolve()'
  - julia -e 'versioninfo(); Pkg.add("FactCheck"); Pkg.add("DataFrames"); Pkg.add("Distributions"); Pkg.add("PyPlot"); Pkg.add("Reexport")'
  - julia ~/.julia/MOpt.jl/test/runtests.jl
